keycloak:
  host: ${KEYCLOAK_HOST:keycloak.localhost}
  realm: ${KEYCLOAK_REALM:energy-app}

spring:
  application:
    name: chat-microservice
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.host}/realms/${keycloak.realm}
  data:
    mongodb:
      username: ${DB_USERNAME:admin}
      password: ${DB_PASSWORD:admin}
      host: ${DB_IP:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_DBNAME:chat_db}
      authentication-database: admin

server:
  port: 8088